-- AlterEnum
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_REPRESENTATIVE_GRANTED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_REPRESENTATIVE_REVOKED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isSchoolRepresentative" BOOLEAN NOT NULL DEFAULT false;
