-- AlterEnum
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_DELETED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_GROUP_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_GROUP_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SCHOOL_GROUP_DELETED';
